/* ═══════════════════════════════════════════════════════════════ */
/* KNOWLEDGE BASE — EXPANSION (PROVISIONAL)                        */
/*                                                                  */
/* AI-drafted, textbook-derived conditions. EVERY entry is           */
/* PROVISIONAL / NEEDS_CLINICAL_REVIEW — the founder verifies tokens, */
/* urgency and exclusions (ideally via the in-app KB Editor).        */
/*                                                                  */
/* ENRICHED 2026-07-13: each condition given a deeper, differentiating*/
/* profile — relevant supportive findings AND contradicting features */
/* (rivals + red-flags that argue against it). No bulk padding: every */
/* token is a genuine feature or a genuine contra for THAT condition. */
/* Enforced by tests/kb-expansion.test.js (reachable req, surfaces,   */
/* no dup, no lint errors) and the token-health guard.               */
/* ICD codes are added at the founder's review step.                 */
/* ═══════════════════════════════════════════════════════════════ */
"use strict";

var KB_EXPANSION = [

/* ═══ RETINA / MEDICAL RETINA ═══ */
{ "name": "Diabetic Macular Edema", "domain": "Retina", "route": "retina",
  "req": ["distortion", "diabetes_history"], "sup": ["central_blur", "reduced_vision", "reduced_contrast", "micropsia", "difficulty_reading", "gradual_blur", "cotton_wool_spots"],
  "con": ["sudden_vision_loss", "pain", "redness", "flashes", "field_loss"], "temporal": ["chronic", "progressive"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Proliferative Diabetic Retinopathy", "domain": "Retina", "route": "urgent",
  "req": ["floaters", "diabetes_history"], "sup": ["sudden_floaters", "reduced_vision", "vision_hazy", "retinal_ischemia", "dark_spots", "field_loss", "cotton_wool_spots"],
  "con": ["pain_severe", "redness", "itching_dominant"], "temporal": ["progressive"], "tests": ["macular_screening_needed"], "urgent": true, "exclusions": [] },
{ "name": "Retinal Artery Macroaneurysm", "domain": "Retina", "route": "retina",
  "req": ["central_blur", "hypertension_history"], "sup": ["distortion", "older_age", "reduced_vision", "sudden_onset", "central_scotoma", "dark_spots"],
  "con": ["pain", "redness", "itching_dominant", "young_age"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Valsalva Retinopathy", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma"], "sup": ["sudden_onset", "reduced_vision", "dark_spots", "central_blur", "recent_viral_history", "floaters"],
  "con": ["pain", "redness", "gradual_onset", "field_loss"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Central Serous Chorioretinopathy (Chronic)", "domain": "Retina", "route": "retina",
  "req": ["distortion", "stress_history"], "sup": ["central_blur", "micropsia", "reduced_contrast", "reduced_vision", "steroid_history", "recurrent_episode"],
  "con": ["older_age", "night_blindness", "pain", "sudden_vision_loss", "field_loss"], "temporal": ["chronic", "recurrent"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Myopic Macular Degeneration", "domain": "Retina", "route": "retina",
  "req": ["central_blur", "myopia"], "sup": ["distortion", "reduced_vision", "progressive_blur", "central_scotoma", "reduced_contrast", "family_history"],
  "con": ["pain", "redness", "sudden_vision_loss", "hyperopia"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Stargardt Disease", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma", "young_age"], "sup": ["central_blur", "color_vision_loss", "family_history", "reduced_vision", "reduced_contrast", "photophobia_mild"],
  "con": ["older_age", "pain", "redness", "sudden_vision_loss", "field_loss"], "temporal": ["progressive"], "tests": [], "exclusions": [] },
{ "name": "Best Vitelliform Dystrophy", "domain": "Retina", "route": "retina",
  "req": ["central_blur", "family_history"], "sup": ["young_age", "distortion", "reduced_vision", "central_scotoma", "reduced_contrast"],
  "con": ["older_age", "pain", "redness", "sudden_vision_loss", "night_blindness"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Cone Dystrophy", "domain": "Retina", "route": "retina",
  "req": ["color_vision_loss"], "sup": ["glare", "central_blur", "photophobia", "reduced_vision", "reduced_contrast", "family_history", "young_age"],
  "con": ["night_blindness", "pain", "redness", "sudden_vision_loss", "field_loss"], "temporal": ["progressive"], "tests": [], "exclusions": [] },
{ "name": "Choroideremia", "domain": "Retina", "route": "retina",
  "req": ["night_blindness", "family_history"], "sup": ["peripheral_field_loss", "young_age", "reduced_contrast", "tunnel_vision", "reduced_vision"],
  "con": ["central_scotoma", "pain", "redness", "sudden_vision_loss", "older_age"], "temporal": ["progressive"], "tests": [], "exclusions": [] },
{ "name": "Degenerative Retinoschisis", "domain": "Retina", "route": "retina",
  "req": ["peripheral_field_loss"], "sup": ["older_age", "peripheral_degeneration", "hyperopia"],
  "con": ["central_blur", "distortion", "pain", "flashes", "curtain_vision", "reduced_vision"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Ocular Ischemic Syndrome", "domain": "Retina", "route": "urgent",
  "req": ["reduced_vision", "retinal_ischemia"], "sup": ["older_age", "pain", "hypertension_history", "diabetes_history", "transient_vision_loss", "rubeosis_iridis"],
  "con": ["young_age", "itching_dominant", "gradual_onset"], "temporal": ["progressive"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Commotio Retinae", "domain": "Retina", "route": "retina",
  "req": ["reduced_vision", "trauma_history"], "sup": ["central_scotoma", "recent_eye_trauma", "central_blur", "field_loss"],
  "con": ["gradual_onset", "itching_dominant", "redness", "chronic_irritation"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Vitreomacular Traction", "domain": "Retina", "route": "retina",
  "req": ["distortion", "older_age"], "sup": ["central_blur", "micropsia", "reduced_vision", "flashes", "reduced_contrast"],
  "con": ["pain", "redness", "sudden_vision_loss", "field_loss", "night_blindness"], "temporal": ["chronic", "progressive"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Solar (Photic) Retinopathy", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma"], "sup": ["central_blur", "micropsia", "reduced_vision", "distortion", "photophobia_mild"],
  "con": ["pain", "redness", "field_loss", "night_blindness", "gradual_onset"], "temporal": ["acute"], "tests": [], "exclusions": [] },

/* ═══ UVEITIS / INFLAMMATION ═══ */
{ "name": "Fuchs Heterochromic Uveitis", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["blur", "chronic_irritation"], "sup": ["floaters", "young_age", "reduced_vision", "heterochromia", "cells_present", "gradual_blur"],
  "con": ["pain_severe", "purulent_discharge", "itching_dominant", "redness"], "temporal": ["chronic"], "tests": ["cells_present"], "exclusions": [] },
{ "name": "Sarcoid Uveitis", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["pain", "recurrent_episode"], "sup": ["photophobia", "redness", "floaters", "autoimmune_history", "reduced_vision", "cells_present", "synechiae"],
  "con": ["purulent_discharge", "itching_dominant"], "temporal": ["chronic", "recurrent"], "tests": ["cells_present"], "exclusions": [] },
{ "name": "Toxoplasma Retinochoroiditis", "domain": "Anterior / Uveitis", "route": "retina",
  "req": ["floaters", "recurrent_episode"], "sup": ["reduced_vision", "vision_hazy", "central_scotoma", "photophobia", "young_age"],
  "con": ["purulent_discharge", "itching_dominant", "redness"], "temporal": ["acute", "recurrent"], "tests": [], "exclusions": [] },
{ "name": "Sympathetic Ophthalmia", "domain": "Anterior / Uveitis", "route": "urgent",
  "req": ["reduced_vision", "trauma_history"], "sup": ["pain", "photophobia", "post_surgery", "floaters", "recent_eye_trauma", "cells_present", "distortion"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["subacute"], "tests": ["cells_present"], "urgent": true, "exclusions": [] },
{ "name": "Pars Planitis", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["floaters", "young_age"], "sup": ["blur", "reduced_vision", "vision_hazy", "dark_spots", "cells_present"],
  "con": ["pain_severe", "purulent_discharge", "itching_dominant", "redness"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Posterior Scleritis", "domain": "Anterior / Uveitis", "route": "urgent",
  "req": ["deep_boring_pain"], "sup": ["reduced_vision", "pain_worse_night", "autoimmune_history", "pain_eye_movement", "redness", "distortion", "proptosis"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["subacute"], "tests": [], "urgent": true, "exclusions": [] },

/* ═══ CORNEA / EXTERNAL ═══ */
{ "name": "Acanthamoeba Keratitis", "domain": "Cornea", "route": "urgent",
  "req": ["pain_severe", "contact_lens_use"], "sup": ["photophobia", "redness", "reduced_vision", "watering", "foreign_body_sensation", "stromal_infiltrate"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["subacute"], "tests": ["stromal_infiltrate"], "urgent": true, "exclusions": [] },
{ "name": "Fungal Keratitis", "domain": "Cornea", "route": "urgent",
  "req": ["pain_severe", "trauma_history"], "sup": ["photophobia", "redness", "reduced_vision", "stromal_infiltrate", "recent_eye_trauma", "watering"],
  "con": ["itching_dominant", "contact_lens_use", "gradual_onset"], "temporal": ["subacute"], "tests": ["stromal_infiltrate"], "urgent": true, "exclusions": [] },
{ "name": "Filamentary Keratitis", "domain": "Cornea", "route": "anterior",
  "req": ["foreign_body_sensation", "dryness"], "sup": ["grittiness", "photophobia_mild", "chronic_irritation", "reduced_tearing", "burning", "recurrent_episode"],
  "con": ["purulent_discharge", "itching_dominant", "pain_severe", "sudden_vision_loss"], "temporal": ["chronic"], "tests": ["schirmer_low"], "exclusions": [] },
{ "name": "Map-Dot-Fingerprint Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["pain_morning"], "sup": ["foreign_body_sensation", "fluctuating_blur", "recurrent_episode", "watering", "photophobia_mild", "family_history"],
  "con": ["purulent_discharge", "itching_dominant", "gradual_blur"], "temporal": ["chronic", "recurrent"], "tests": [], "exclusions": [] },
{ "name": "Lattice Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity", "family_history"], "sup": ["reduced_vision", "recurrent_episode", "pain_morning", "gradual_blur", "foreign_body_sensation", "glare"],
  "con": ["purulent_discharge", "itching_dominant", "redness"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Granular Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity", "family_history"], "sup": ["glare", "gradual_blur", "reduced_vision", "photophobia_mild", "foreign_body_sensation"],
  "con": ["purulent_discharge", "itching_dominant", "pain_severe", "redness"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Terrien Marginal Degeneration", "domain": "Cornea", "route": "anterior",
  "req": ["irregular_astigmatism"], "sup": ["peripheral_degeneration", "gradual_blur", "reduced_vision", "ghosting", "older_age"],
  "con": ["pain_severe", "purulent_discharge", "redness", "sudden_vision_loss"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Superior Limbic Keratoconjunctivitis", "domain": "Cornea", "route": "surface",
  "req": ["foreign_body_sensation", "thyroid_history"], "sup": ["redness", "watering", "chronic_irritation", "burning", "photophobia_mild", "recurrent_episode"],
  "con": ["purulent_discharge", "pain_severe", "reduced_vision"], "temporal": ["chronic", "recurrent"], "tests": [], "exclusions": [] },

/* ═══ GLAUCOMA ═══ */
{ "name": "Steroid-Induced Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "steroid_history"], "sup": ["raised_iop_risk", "increased_cd", "field_defect", "halos", "gradual_blur", "cd_asymmetry"],
  "con": ["pain_severe", "redness", "normal_iop", "itching_dominant"], "temporal": ["subacute", "chronic"], "tests": ["increased_cd"], "exclusions": [] },
{ "name": "Angle Recession Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "trauma_history"], "sup": ["cd_asymmetry", "recent_eye_trauma", "increased_cd", "field_defect", "reduced_vision", "hyphema_visible"],
  "con": ["itching_dominant", "normal_iop", "bilateral"], "temporal": ["chronic"], "tests": ["increased_cd"], "exclusions": [] },
{ "name": "Juvenile Open Angle Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "young_age"], "sup": ["family_history", "myopia", "increased_cd", "nrr_thinning", "field_defect", "cd_asymmetry"],
  "con": ["older_age", "pain_severe", "redness", "normal_iop"], "temporal": ["chronic", "progressive"], "tests": ["increased_cd", "nrr_thinning"], "exclusions": [] },

/* ═══ NEURO-OPHTHALMOLOGY ═══ */
{ "name": "Giant Cell Arteritis (Arteritic AION)", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["sudden_vision_loss", "older_age"], "sup": ["headache", "pain", "transient_vision_loss", "jaw_claudication", "scalp_tenderness", "reduced_vision", "diplopia"],
  "con": ["young_age", "itching_dominant", "redness", "gradual_onset"], "temporal": ["acute"], "tests": ["disc_edema"], "urgent": true, "exclusions": [] },
{ "name": "Idiopathic Intracranial Hypertension", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["bilateral_disc_swelling"], "sup": ["headache", "transient_vision_loss", "vomiting", "young_age", "reduced_contrast", "field_defect"],
  "con": ["older_age", "pain_severe", "redness", "itching_dominant"], "temporal": ["subacute", "progressive"], "tests": ["disc_edema"], "urgent": true, "exclusions": [] },
{ "name": "Pituitary Adenoma (Chiasmal Compression)", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["temporal_field_loss", "headache"], "sup": ["reduced_vision", "color_vision_loss", "reduced_contrast", "field_defect", "diplopia"],
  "con": ["pain_severe", "redness", "itching_dominant", "field_loss_half"], "temporal": ["progressive"], "tests": ["visual_field_defect"], "exclusions": [] },
{ "name": "Ocular Myasthenia Gravis", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["ptosis", "worse_evening"], "sup": ["diplopia", "fatigue", "variable_blur", "vertical_diplopia", "intermittent_diplopia", "restricted_motility"],
  "con": ["anisocoria", "pain_severe", "redness", "reduced_vision"], "temporal": ["intermittent"], "tests": [], "exclusions": [] },
{ "name": "Nutritional / Toxic Optic Neuropathy", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["central_scotoma", "toxic_optic_risk"], "sup": ["color_vision_loss", "reduced_vision", "progressive_vision_loss", "reduced_contrast", "bilateral"],
  "con": ["pain_severe", "redness", "sudden_vision_loss", "field_loss_half"], "temporal": ["progressive"], "tests": ["visual_field_defect"], "exclusions": [] },
{ "name": "Leber Hereditary Optic Neuropathy", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["central_scotoma", "family_history"], "sup": ["young_age", "color_vision_loss", "reduced_vision", "progressive_vision_loss", "reduced_contrast"],
  "con": ["older_age", "pain_severe", "redness", "field_loss_half"], "temporal": ["subacute"], "tests": [], "exclusions": [] },
{ "name": "Idiopathic Orbital Inflammation (Pseudotumor)", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["proptosis", "pain_eye_movement"], "sup": ["redness", "diplopia", "restricted_motility", "reduced_vision", "pain", "tenderness"],
  "con": ["itching_dominant", "gradual_onset", "thyroid_history"], "temporal": ["acute", "subacute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Adie Tonic Pupil", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["anisocoria"], "sup": ["photophobia_mild", "difficulty_focusing", "young_age", "blur_near", "near_strain"],
  "con": ["ptosis", "pain_severe", "reduced_vision", "diplopia"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ LENS ═══ */
{ "name": "Anterior Polar Cataract", "domain": "Lens", "route": "lens",
  "req": ["gradual_blur", "family_history"], "sup": ["glare", "reduced_vision", "young_age", "ghosting"],
  "con": ["sudden_vision_loss", "pain", "redness", "distortion", "flashes", "field_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Phacomorphic Angle Closure", "domain": "Lens", "route": "urgent",
  "req": ["high_iop", "narrow_angle"], "sup": ["pain_severe", "halos", "reduced_vision", "older_age", "redness", "vomiting", "corneal_edema", "gradual_blur"],
  "con": ["itching_dominant", "gradual_onset", "normal_iop"], "temporal": ["acute"], "tests": ["IOP_very_high"], "urgent": true, "exclusions": [] },

/* ═══ OCULOPLASTICS / SURFACE ═══ */
{ "name": "Floppy Eyelid Syndrome", "domain": "Surface & Lids", "route": "surface",
  "req": ["chronic_irritation", "morning_stickiness"], "sup": ["redness", "foreign_body_sensation", "discharge", "morning_stickiness", "dryness", "lid_margin_irregularity"],
  "con": ["pain_severe", "reduced_vision", "proptosis", "sudden_vision_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Blepharospasm", "domain": "Surface & Lids", "route": "surface",
  "req": ["spasm"], "sup": ["photophobia", "irritation", "chronic_irritation", "dryness", "bilateral", "worse_evening"],
  "con": ["pain_severe", "reduced_vision", "proptosis", "diplopia"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Canaliculitis", "domain": "Surface & Lids", "route": "surface",
  "req": ["medial_canthus_swelling", "recurrent_episode"], "sup": ["discharge", "tearing", "redness", "excess_tearing", "tenderness", "chronic_irritation"],
  "con": ["proptosis", "restricted_motility", "reduced_vision", "diplopia"], "temporal": ["chronic", "recurrent"], "tests": [], "exclusions": [] },
{ "name": "Sebaceous Gland Carcinoma", "domain": "Surface & Lids", "route": "urgent",
  "req": ["painless_lid_nodule", "recurrent_episode"], "sup": ["lash_loss", "older_age", "chronic_irritation", "redness", "lid_margin_irregularity"],
  "con": ["pain", "itching_dominant", "young_age", "sudden_onset"], "temporal": ["chronic", "progressive"], "tests": [], "urgent": true, "exclusions": [] },

/* ═══ BINOCULAR VISION / STRABISMUS ═══ */
{ "name": "Basic Exotropia", "domain": "Binocular Vision", "route": "binocular",
  "req": ["exo_distance"], "sup": ["exo_near", "intermittent_eye_out", "closing_one_eye", "asthenopia", "worse_distance", "squinting", "suppression"],
  "con": ["eye_inward", "constant_deviation", "reduced_vision"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Sensory Strabismus", "domain": "Binocular Vision", "route": "binocular",
  "req": ["constant_deviation"], "sup": ["reduced_vision", "suppression", "unequal_vision", "trauma_history", "young_age", "closing_one_eye"],
  "con": ["intermittent_eye_out", "asthenopia", "diplopia"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Decompensated Phoria", "domain": "Binocular Vision", "route": "binocular",
  "req": ["intermittent_diplopia"], "sup": ["asthenopia", "headache_near", "eye_strain", "worse_evening", "fatigue", "difficulty_reading", "double_vision_near"],
  "con": ["constant_deviation", "reduced_vision", "sudden_onset"], "temporal": ["intermittent"], "tests": ["reduced_vergence_ranges"], "exclusions": [] },

/* ═══ Binocular / accommodative / strabismus (batch 2) ═══ */
{ "name": "Amblyopia (Refractive)", "domain": "Binocular Vision", "route": "binocular",
  "req": ["unequal_vision", "unequal_refractive_error"], "sup": ["young_age", "suppression", "reduced_vision", "family_history", "squinting"],
  "con": ["sudden_onset", "pain", "redness", "distortion", "field_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Consecutive Exotropia", "domain": "Binocular Vision", "route": "binocular",
  "req": ["exo_distance", "post_surgery"], "sup": ["intermittent_eye_out", "asthenopia", "closing_one_eye", "diplopia", "suppression"],
  "con": ["eye_inward", "reduced_vision", "pain"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Accommodative Esotropia", "domain": "Binocular Vision", "route": "binocular",
  "req": ["eso_near", "high_ACA_ratio"], "sup": ["young_age", "hyperopia", "asthenopia", "headache_near", "difficulty_reading", "intermittent_diplopia"],
  "con": ["exo_distance", "reduced_vision", "older_age"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Convergence Paralysis", "domain": "Binocular Vision", "route": "binocular",
  "req": ["double_vision_near", "reduced_PFV"], "sup": ["asthenopia", "headache_near", "near_strain", "difficulty_reading", "sudden_onset"],
  "con": ["distance_diplopia", "reduced_vision", "constant_deviation"], "temporal": ["subacute"], "tests": [], "exclusions": [] },
{ "name": "Vertical Heterophoria", "domain": "Binocular Vision", "route": "binocular",
  "req": ["vertical_diplopia", "head_tilt"], "sup": ["asthenopia", "headache", "worse_evening", "fatigue", "reading_difficulty", "intermittent_diplopia"],
  "con": ["horizontal_diplopia", "reduced_vision", "constant_deviation"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ Refractive (batch 2) ═══ */
{ "name": "Anisometropic Refractive Error", "domain": "Refractive", "route": "refractive",
  "req": ["unequal_refractive_error"], "sup": ["unequal_vision", "asthenopia", "headache", "suppression", "young_age", "improves_with_correction"],
  "con": ["reduced_vision", "distortion", "field_loss", "pain", "redness"], "temporal": ["chronic"], "tests": ["refraction_difference"], "exclusions": [] },
{ "name": "Pseudomyopia (Accommodative Spasm)", "domain": "Refractive", "route": "refractive",
  "req": ["distance_blur", "spasm"], "sup": ["near_strain", "variable_blur", "screen_use_exacerbation", "headache", "fluctuating_blur", "worse_evening"],
  "con": ["reduced_vision", "distortion", "field_loss", "night_blindness", "older_age"], "temporal": ["intermittent"], "tests": [], "exclusions": [] },
{ "name": "Post-Refractive-Surgery Ectasia", "domain": "Refractive", "route": "refractive",
  "req": ["irregular_astigmatism", "post_surgery"], "sup": ["progressive_blur", "ghosting", "glare", "reduced_vision", "fluctuating_blur", "halos"],
  "con": ["pain_severe", "redness", "sudden_vision_loss", "field_loss"], "temporal": ["progressive"], "tests": [], "exclusions": [] },

/* ═══ Conjunctiva / sclera / surface (batch 2) ═══ */
{ "name": "Conjunctival Melanoma", "domain": "Surface & Lids", "route": "urgent",
  "req": ["pigmented_lesion", "elevated_mass"], "sup": ["redness", "older_age", "localized_conjunctival_elevation", "foreign_body_sensation"],
  "con": ["itching_dominant", "young_age", "sudden_onset", "watering"], "temporal": ["progressive"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Ocular Surface Squamous Neoplasia", "domain": "Surface & Lids", "route": "urgent",
  "req": ["elevated_mass", "conjunctival_growth_cornea"], "sup": ["redness", "older_age", "foreign_body_sensation", "irritation", "reduced_vision"],
  "con": ["itching_dominant", "young_age", "purulent_discharge"], "temporal": ["progressive"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Conjunctival Nevus", "domain": "Surface & Lids", "route": "surface",
  "req": ["pigmented_lesion"], "sup": ["localized_conjunctival_elevation", "young_age", "irritation"],
  "con": ["elevated_mass", "reduced_vision", "pain_severe", "sudden_onset", "field_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Giant Papillary Conjunctivitis", "domain": "Surface & Lids", "route": "surface",
  "req": ["contact_lens_use", "itching_dominant"], "sup": ["ropy_discharge", "foreign_body_sensation", "reduced_wear_time", "redness", "chronic_irritation", "giant_papillae"],
  "con": ["pain_severe", "reduced_vision", "purulent_discharge"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Ligneous Conjunctivitis", "domain": "Surface & Lids", "route": "surface",
  "req": ["redness", "recurrent_episode"], "sup": ["discharge", "young_age", "foreign_body_sensation", "chronic_irritation", "watering"],
  "con": ["pain_severe", "reduced_vision", "sudden_vision_loss"], "temporal": ["chronic", "recurrent"], "tests": [], "exclusions": [] },

/* ═══ Lacrimal / lids (batch 2) ═══ */
{ "name": "Punctal Stenosis", "domain": "Surface & Lids", "route": "surface",
  "req": ["excess_tearing", "older_age"], "sup": ["irritation", "chronic_irritation", "tearing", "watering", "blur"],
  "con": ["reduced_vision", "pain_severe", "purulent_discharge", "proptosis"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Nasolacrimal Duct Obstruction (Congenital)", "domain": "Surface & Lids", "route": "surface",
  "req": ["excess_tearing", "young_age"], "sup": ["discharge", "morning_stickiness", "recurrent_episode", "tearing", "medial_canthus_swelling"],
  "con": ["reduced_vision", "pain_severe", "older_age", "proptosis"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Dacryoadenitis", "domain": "Surface & Lids", "route": "surface",
  "req": ["localized_lid_swelling", "tenderness"], "sup": ["redness", "pain", "fever", "recent_viral_history", "tearing"],
  "con": ["proptosis", "restricted_motility", "reduced_vision", "diplopia", "pain_eye_movement"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Involutional Ptosis", "domain": "Surface & Lids", "route": "surface",
  "req": ["ptosis", "older_age"], "sup": ["reading_difficulty", "fatigue", "worse_evening", "difficulty_reading"],
  "con": ["diplopia", "anisocoria", "pain_severe", "sudden_onset", "reduced_vision"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Eyelid Basal Cell Carcinoma", "domain": "Surface & Lids", "route": "urgent",
  "req": ["painless_lid_nodule", "older_age"], "sup": ["lash_loss", "chronic_irritation", "cracking_skin", "redness", "lid_margin_irregularity"],
  "con": ["pain", "itching_dominant", "young_age", "sudden_onset"], "temporal": ["progressive"], "tests": [], "urgent": true, "exclusions": [] },

/* ═══ Cornea (surface/contact-lens) (batch 2) ═══ */
{ "name": "Contact Lens Corneal Warpage", "domain": "Cornea", "route": "anterior",
  "req": ["contact_lens_use", "irregular_astigmatism"], "sup": ["fluctuating_blur", "ghosting", "reduced_wear_time", "distance_blur", "improves_with_correction"],
  "con": ["pain_severe", "redness", "purulent_discharge", "reduced_vision"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Corneal Foreign Body (Metallic)", "domain": "Cornea", "route": "anterior",
  "req": ["foreign_body_sensation", "trauma_history"], "sup": ["pain_acute", "watering", "redness", "photophobia_mild", "high_speed_particle", "recent_eye_trauma"],
  "con": ["itching_dominant", "gradual_onset", "reduced_vision"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Vortex Keratopathy (Drug-Induced)", "domain": "Cornea", "route": "anterior",
  "req": ["glare", "corneal_opacity"], "sup": ["halos", "gradual_blur", "older_age", "reduced_contrast"],
  "con": ["pain_severe", "redness", "purulent_discharge", "sudden_vision_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Iron Line (Corneal)", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity_band"], "sup": ["astigmatism", "irregular_astigmatism", "chronic_irritation"],
  "con": ["pain_severe", "reduced_vision", "purulent_discharge", "redness"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Limbal Stem Cell Deficiency", "domain": "Cornea", "route": "anterior",
  "req": ["new_vessels_cornea", "chronic_irritation"], "sup": ["reduced_vision", "photophobia", "recurrent_episode", "redness", "foreign_body_sensation", "watering"],
  "con": ["itching_dominant", "sudden_onset"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },

/* ═══ Retina / vascular (batch 2) ═══ */
{ "name": "Hemiretinal Vein Occlusion", "domain": "Retina", "route": "retina",
  "req": ["sectoral_blur", "hypertension_history"], "sup": ["reduced_vision", "distortion", "older_age", "sudden_onset", "field_loss", "dark_spots"],
  "con": ["pain", "redness", "itching_dominant", "gradual_onset"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Retinal Vasculitis", "domain": "Retina", "route": "retina",
  "req": ["floaters", "autoimmune_history"], "sup": ["reduced_vision", "vision_hazy", "reduced_contrast", "dark_spots", "photophobia", "young_age"],
  "con": ["purulent_discharge", "itching_dominant", "pain_severe"], "temporal": ["subacute"], "tests": [], "exclusions": [] },
{ "name": "Retinopathy of Prematurity (Cicatricial)", "domain": "Retina", "route": "retina",
  "req": ["reduced_vision", "young_age"], "sup": ["myopia", "peripheral_field_loss", "risk_detachment", "family_history"],
  "con": ["older_age", "pain", "redness", "gradual_onset"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Choroidal Hemangioma", "domain": "Retina", "route": "retina",
  "req": ["distortion", "elevated_mass"], "sup": ["central_blur", "reduced_vision", "field_loss", "hyperopia"],
  "con": ["pain", "redness", "itching_dominant", "sudden_vision_loss"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Gyrate Atrophy", "domain": "Retina", "route": "retina",
  "req": ["night_blindness", "myopia"], "sup": ["peripheral_field_loss", "family_history", "young_age", "reduced_contrast", "tunnel_vision"],
  "con": ["central_scotoma", "pain", "redness", "sudden_vision_loss", "older_age"], "temporal": ["progressive"], "tests": [], "exclusions": [] },
{ "name": "Birdshot Chorioretinopathy", "domain": "Retina", "route": "retina",
  "req": ["floaters", "night_blindness"], "sup": ["reduced_contrast", "reduced_vision", "distortion", "dark_spots", "autoimmune_history"],
  "con": ["pain_severe", "purulent_discharge", "redness", "sudden_vision_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ Neuro-ophthalmology / motility (batch 2) ═══ */
{ "name": "Downbeat Nystagmus", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["nystagmus_other_eye", "shadowing"], "sup": ["visual_disturbance", "reduced_vision", "oscillopsia", "head_tilt"],
  "con": ["pain_severe", "redness", "itching_dominant"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Skew Deviation", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["vertical_diplopia", "head_tilt"], "sup": ["visual_disturbance", "reduced_vision", "sudden_onset", "oscillopsia", "older_age"],
  "con": ["itching_dominant", "redness", "gradual_onset"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Chronic Progressive External Ophthalmoplegia", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["ptosis", "restricted_motility"], "sup": ["family_history", "diplopia", "bilateral", "reduced_stamina", "worse_evening"],
  "con": ["pain_severe", "redness", "sudden_onset", "anisocoria"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Convergence-Retraction Nystagmus (Dorsal Midbrain)", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["difficulty_focusing", "vertical_diplopia"], "sup": ["diplopia", "headache", "vomiting", "oscillopsia", "young_age"],
  "con": ["itching_dominant", "redness", "gradual_onset"], "temporal": ["subacute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Hemianopic Field Loss (Occipital Stroke)", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["field_loss_half", "sudden_onset"], "sup": ["older_age", "hypertension_history", "reduced_vision", "diabetes_history", "visual_disturbance"],
  "con": ["pain_severe", "redness", "itching_dominant", "gradual_onset"], "temporal": ["acute"], "tests": ["visual_field_defect"], "urgent": true, "exclusions": [] },

/* ═══ Glaucoma / lens (batch 2) ═══ */
{ "name": "Neovascular Glaucoma (Diabetic)", "domain": "Glaucoma", "route": "urgent",
  "req": ["high_iop", "rubeosis_iridis"], "sup": ["diabetes_history", "pain_severe", "reduced_vision", "halos", "redness", "retinal_ischemia", "corneal_edema"],
  "con": ["itching_dominant", "normal_iop", "gradual_onset"], "temporal": ["subacute"], "tests": ["IOP_very_high"], "urgent": true, "exclusions": [] },
{ "name": "Aphakic Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "post_surgery"], "sup": ["halos", "cd_asymmetry", "increased_cd", "reduced_vision", "field_defect", "glare"],
  "con": ["itching_dominant", "normal_iop", "redness"], "temporal": ["chronic"], "tests": ["increased_cd"], "exclusions": [] },
{ "name": "Ectopia Lentis (Marfan)", "domain": "Lens", "route": "lens",
  "req": ["lens_displacement", "young_age"], "sup": ["fluctuating_blur", "irregular_astigmatism", "family_history", "ghosting", "reduced_vision", "high_iop"],
  "con": ["pain_severe", "redness", "purulent_discharge", "older_age"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Posterior Polar Cataract", "domain": "Lens", "route": "lens",
  "req": ["gradual_blur", "glare"], "sup": ["family_history", "difficulty_near", "reduced_vision", "halos", "ghosting"],
  "con": ["sudden_vision_loss", "pain", "redness", "distortion", "flashes"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ Ocular trauma (batch 3) ═══ */
{ "name": "Chemical Eye Burn", "domain": "Cornea", "route": "urgent",
  "req": ["chemical_splash"], "sup": ["pain_severe", "redness", "reduced_vision", "watering", "photophobia", "foreign_body_sensation", "corneal_edema"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Open Globe Injury", "domain": "Cornea", "route": "urgent",
  "req": ["recent_eye_trauma", "reduced_vision"], "sup": ["pain_severe", "redness", "high_speed_particle", "hyphema_visible", "watering", "photophobia"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Traumatic Hyphema", "domain": "Anterior / Uveitis", "route": "urgent",
  "req": ["hyphema_visible"], "sup": ["recent_eye_trauma", "pain", "reduced_vision", "photophobia", "high_iop", "redness"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Intraocular Foreign Body", "domain": "Cornea", "route": "urgent",
  "req": ["high_speed_particle", "pain"], "sup": ["reduced_vision", "redness", "foreign_body_sensation", "recent_eye_trauma", "watering", "floaters"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Corneal Laceration", "domain": "Cornea", "route": "urgent",
  "req": ["recent_eye_trauma", "pain_severe"], "sup": ["watering", "redness", "reduced_vision", "photophobia", "foreign_body_sensation", "high_speed_particle"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Orbital Blowout Fracture", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["recent_eye_trauma", "vertical_diplopia"], "sup": ["restricted_motility", "reduced_vision", "diplopia", "pain_eye_movement", "trauma_history"],
  "con": ["itching_dominant", "gradual_onset", "redness"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Traumatic Optic Neuropathy", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["recent_eye_trauma", "color_vision_loss"], "sup": ["reduced_vision", "central_scotoma", "trauma_history", "field_defect", "reduced_contrast"],
  "con": ["itching_dominant", "gradual_onset", "redness"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Traumatic Mydriasis", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["recent_eye_trauma", "anisocoria"], "sup": ["photophobia_mild", "difficulty_focusing", "trauma_history", "blur_near"],
  "con": ["ptosis", "gradual_onset", "itching_dominant", "diplopia"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Choroidal Rupture", "domain": "Retina", "route": "retina",
  "req": ["recent_eye_trauma", "central_blur"], "sup": ["reduced_vision", "distortion", "trauma_history", "central_scotoma"],
  "con": ["itching_dominant", "gradual_onset", "redness"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Ocular Siderosis (Retained IOFB)", "domain": "Retina", "route": "retina",
  "req": ["high_speed_particle", "gradual_blur"], "sup": ["night_blindness", "reduced_vision", "trauma_history", "peripheral_field_loss", "high_iop"],
  "con": ["itching_dominant", "sudden_onset", "redness"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Thermal Eyelid Burn", "domain": "Surface & Lids", "route": "surface",
  "req": ["recent_eye_trauma", "localized_lid_swelling"], "sup": ["pain", "redness", "chemical_splash", "tenderness", "lash_loss"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation", "reduced_vision"], "temporal": ["acute"], "tests": [], "exclusions": [] },

/* ═══ Systemic / vascular retinopathy (batch 3) ═══ */
{ "name": "Malignant Hypertensive Retinopathy", "domain": "Retina", "route": "urgent",
  "req": ["cotton_wool_spots", "hypertension_history"], "sup": ["reduced_vision", "headache", "distortion", "arteriolar_changes", "disc_edema", "older_age"],
  "con": ["itching_dominant", "pain_severe", "redness", "gradual_onset"], "temporal": ["subacute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Purtscher Retinopathy", "domain": "Retina", "route": "retina",
  "req": ["cotton_wool_spots", "recent_eye_trauma"], "sup": ["reduced_vision", "central_scotoma", "trauma_history", "sudden_onset"],
  "con": ["itching_dominant", "redness", "gradual_onset", "pain_severe"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Giant Cell Arteritis (Occult / Systemic)", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["jaw_claudication", "scalp_tenderness"], "sup": ["older_age", "headache", "transient_vision_loss", "reduced_vision", "diplopia", "pain"],
  "con": ["young_age", "itching_dominant", "redness"], "temporal": ["subacute"], "tests": [], "urgent": true, "exclusions": [] },

/* ═══ Optic nerve / retina (batch 3) ═══ */
{ "name": "Optic Pit Maculopathy", "domain": "Retina", "route": "retina",
  "req": ["optic_pit"], "sup": ["central_blur", "distortion", "reduced_vision", "micropsia", "central_scotoma", "young_age"],
  "con": ["pain", "redness", "sudden_vision_loss", "field_loss"], "temporal": ["chronic"], "tests": ["macular_screening_needed"], "exclusions": [] },

/* ═══ Neuro-ophthalmology (nystagmus / oscillopsia) (batch 3) ═══ */
{ "name": "Acquired Pendular Nystagmus", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["oscillopsia"], "sup": ["reduced_vision", "ms_history", "visual_disturbance", "nystagmus_other_eye", "shadowing"],
  "con": ["pain_severe", "redness", "itching_dominant"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Spasmus Nutans", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["oscillopsia", "young_age"], "sup": ["head_tilt", "visual_disturbance", "nystagmus_other_eye"],
  "con": ["older_age", "pain_severe", "redness", "reduced_vision"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Superior Oblique Myokymia", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["oscillopsia", "intermittent_diplopia"], "sup": ["vertical_diplopia", "visual_disturbance", "shadowing"],
  "con": ["constant_deviation", "pain_severe", "redness", "reduced_vision"], "temporal": ["intermittent"], "tests": [], "exclusions": [] },

/* ═══ Cornea / ocular surface (immune / surgical) (batch 3) ═══ */
{ "name": "Ocular Rosacea", "domain": "Surface & Lids", "route": "surface",
  "req": ["chronic_redness", "lid_margin_irregularity"], "sup": ["burning", "dryness", "recurrent_episode", "foreign_body_sensation", "cracking_skin", "chronic_irritation"],
  "con": ["purulent_discharge", "reduced_vision", "sudden_vision_loss", "itching_dominant"], "temporal": ["chronic", "recurrent"], "tests": [], "exclusions": [] },
{ "name": "Mooren Ulcer", "domain": "Cornea", "route": "urgent",
  "req": ["peripheral_infiltrate", "pain_severe"], "sup": ["redness", "reduced_vision", "photophobia", "watering", "peripheral_degeneration", "older_age"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["progressive"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Peripheral Ulcerative Keratitis", "domain": "Cornea", "route": "urgent",
  "req": ["peripheral_infiltrate", "autoimmune_history"], "sup": ["pain", "redness", "reduced_vision", "photophobia", "peripheral_degeneration", "watering"],
  "con": ["itching_dominant", "gradual_onset", "contact_lens_use"], "temporal": ["subacute", "progressive"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Toxic Anterior Segment Syndrome", "domain": "Anterior / Uveitis", "route": "urgent",
  "req": ["post_surgery", "corneal_edema"], "sup": ["redness", "reduced_vision", "pain", "cells_present", "photophobia", "blur"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": ["cells_present"], "urgent": true, "exclusions": [] },
{ "name": "Vernal Shield Ulcer", "domain": "Cornea", "route": "anterior",
  "req": ["itching_dominant", "corneal_opacity"], "sup": ["photophobia", "reduced_vision", "young_age", "watering", "giant_papillae", "ropy_discharge"],
  "con": ["purulent_discharge", "older_age", "pain_severe"], "temporal": ["recurrent"], "tests": [], "exclusions": [] },
{ "name": "Contact Lens Acute Red Eye (CLARE)", "domain": "Cornea", "route": "anterior",
  "req": ["contact_lens_use", "redness"], "sup": ["pain", "photophobia", "watering", "reduced_wear_time", "foreign_body_sensation", "sudden_onset"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["acute"], "tests": [], "exclusions": [] },

/* ═══ BATCH 4 (2026-07-15) — high-yield gaps, each with a SPECIFIC required
   token so it can't cross-fire into unrelated presentations. Provisional /
   NEEDS_CLINICAL_REVIEW; urgency flags in particular need founder sign-off. ═══ */

/* Uveitis / inflammatory */
{ "name": "Vogt-Koyanagi-Harada Disease", "domain": "Anterior / Uveitis", "route": "urgent",
  "req": ["subretinal_fluid", "headache"], "sup": ["reduced_vision", "bilateral", "photophobia", "floaters", "redness", "recurrent_episode"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["acute"], "tests": ["cells_present"], "urgent": true, "exclusions": [] },
{ "name": "Behcet Disease (Ocular)", "domain": "Anterior / Uveitis", "route": "urgent",
  "req": ["hypopyon", "recurrent_episode"], "sup": ["pain", "redness", "floaters", "reduced_vision", "photophobia", "retinal_ischemia"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["recurrent", "acute"], "tests": ["cells_present"], "urgent": true, "exclusions": [] },

/* Medical / vascular retina */
{ "name": "Coats Disease", "domain": "Retina", "route": "retina",
  "req": ["leukocoria", "young_age"], "sup": ["reduced_vision", "hard_exudates", "dilated_tortuous_veins", "floaters", "eye_inward"],
  "con": ["older_age", "pain", "redness", "bilateral", "itching_dominant"], "temporal": ["progressive"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Sickle Cell Retinopathy", "domain": "Retina", "route": "retina",
  "req": ["nve_neovascularization_elsewhere", "retinal_ischemia"], "sup": ["floaters", "reduced_vision", "vitreous_hemorrhage", "sudden_floaters", "dark_spots"],
  "con": ["pain", "redness", "itching_dominant", "gradual_onset"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Angioid Streaks", "domain": "Retina", "route": "retina",
  "req": ["distortion", "subretinal_hemorrhage_cnv"], "sup": ["central_blur", "reduced_vision", "central_scotoma", "reduced_contrast", "micropsia"],
  "con": ["pain", "redness", "night_blindness", "itching_dominant"], "temporal": ["chronic"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Ocular Histoplasmosis Syndrome (POHS)", "domain": "Retina", "route": "retina",
  "req": ["subretinal_hemorrhage_cnv", "peripapillary_atrophy_beta_zone"], "sup": ["central_blur", "distortion", "reduced_vision", "central_scotoma"],
  "con": ["pain", "redness", "floaters", "itching_dominant"], "temporal": ["chronic"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Multiple Evanescent White Dot Syndrome (MEWDS)", "domain": "Retina", "route": "retina",
  "req": ["flashes", "young_age"], "sup": ["central_scotoma", "reduced_vision", "recent_viral_history", "temporal_field_loss", "central_blur"],
  "con": ["pain", "redness", "older_age", "night_blindness"], "temporal": ["acute"], "tests": [], "exclusions": [] },

/* Cornea / surgical */
{ "name": "Corneal Graft Rejection", "domain": "Cornea", "route": "urgent",
  "req": ["post_surgery", "corneal_edema"], "sup": ["redness", "pain", "reduced_vision", "photophobia", "ciliary_flush", "recurrent_episode"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["acute", "subacute"], "tests": ["cells_present"], "urgent": true, "exclusions": [] },
{ "name": "Uveitis-Glaucoma-Hyphema (UGH) Syndrome", "domain": "Glaucoma", "route": "anterior",
  "req": ["hyphema", "post_surgery"], "sup": ["high_iop", "redness", "pain", "reduced_vision", "iol_sulcus", "recurrent_episode"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["recurrent", "subacute"], "tests": ["iol_decentered", "cells_present"], "exclusions": [] },

/* Neuro-orbital */
{ "name": "Carotid-Cavernous Fistula", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["proptosis", "dilated_tortuous_veins"], "sup": ["redness", "diplopia", "high_iop", "chronic_redness", "chemosis", "conjunctival_edema"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_blur"], "temporal": ["chronic", "subacute"], "tests": ["restricted_motility"], "urgent": true, "exclusions": [] },

/* ═══ BATCH 5 (2026-07-15) — high-yield gaps, specific required tokens +
   clinically-meaningful contradictors so they slot in without cross-firing.
   Provisional / NEEDS_CLINICAL_REVIEW; urgency flags need founder sign-off. ═══ */

/* Glaucoma / anterior-segment */
{ "name": "Posner-Schlossman Syndrome (Glaucomatocyclitic Crisis)", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "recurrent_episode"], "sup": ["halos", "blur", "pain", "corneal_edema", "cells_present", "reduced_vision"],
  "con": ["synechiae", "itching_dominant", "purulent_discharge"], "temporal": ["recurrent", "acute"], "tests": ["IOP_very_high", "cells_present"], "exclusions": [] },
{ "name": "Iridocorneal Endothelial (ICE) Syndrome", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["corneal_edema", "iris_atrophy"], "sup": ["high_iop", "blur", "reduced_vision", "glare", "older_age", "heterochromia"],
  "con": ["pain_severe", "itching_dominant", "bilateral"], "temporal": ["chronic", "progressive"], "tests": ["guttata"], "exclusions": [] },
{ "name": "Malignant Glaucoma (Aqueous Misdirection)", "domain": "Glaucoma", "route": "urgent",
  "req": ["high_iop", "post_surgery"], "sup": ["shallow_ac", "pain", "reduced_vision", "blur", "redness"],
  "con": ["itching_dominant", "gradual_onset", "normal_iop"], "temporal": ["acute", "subacute"], "tests": ["IOP_very_high", "shallow_ac"], "urgent": true, "exclusions": [] },

/* Neuro-ophthalmic / orbital */
{ "name": "Neuroretinitis", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["reduced_vision", "disc_edema"], "sup": ["central_scotoma", "color_vision_loss", "macular_star", "recent_viral_history", "RAPD_positive"],
  "con": ["pain_severe", "itching_dominant", "night_blindness"], "temporal": ["acute"], "tests": ["macular_star", "disc_edema"], "exclusions": [] },
{ "name": "Papillophlebitis", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["disc_edema", "young_age"], "sup": ["blur", "reduced_vision", "flame_hemorrhages", "dilated_tortuous_veins", "transient_vision_loss"],
  "con": ["pain_severe", "older_age", "itching_dominant"], "temporal": ["acute", "subacute"], "tests": ["disc_edema"], "exclusions": [] },
{ "name": "Tolosa-Hunt Syndrome", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["pain_eye_movement", "diplopia"], "sup": ["ptosis", "restricted_motility", "headache", "pain", "recurrent_episode"],
  "con": ["itching_dominant", "redness", "gradual_onset"], "temporal": ["acute", "recurrent"], "tests": ["restricted_motility"], "exclusions": [] },
{ "name": "Cavernous Sinus Thrombosis", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["proptosis", "diplopia"], "sup": ["ptosis", "pain", "restricted_motility", "headache", "reduced_vision", "fever"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": ["restricted_motility"], "urgent": true, "exclusions": [] },

/* Ocular surface */
{ "name": "Chlamydial (Adult Inclusion) Conjunctivitis", "domain": "Surface & Lids", "route": "surface",
  "req": ["follicles", "chronic_redness"], "sup": ["watery_discharge", "preauricular_node", "foreign_body_sensation", "recurrent_episode", "watering"],
  "con": ["itching_dominant", "purulent_discharge", "sudden_onset"], "temporal": ["chronic", "subacute"], "tests": ["follicles", "preauricular_lymph_node"], "exclusions": [] },
{ "name": "Ocular Cicatricial Pemphigoid", "domain": "Surface & Lids", "route": "surface",
  "req": ["chronic_redness", "dryness"], "sup": ["foreign_body_sensation", "reduced_tearing", "recurrent_episode", "trichiasis", "entropion"],
  "con": ["itching_dominant", "sudden_onset", "purulent_discharge"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Toxic Keratoconjunctivitis (Medicamentosa)", "domain": "Surface & Lids", "route": "surface",
  "req": ["chronic_redness", "punctate_staining"], "sup": ["foreign_body_sensation", "burning", "follicles", "chronic_irritation", "tearing"],
  "con": ["itching_dominant", "purulent_discharge", "sudden_onset"], "temporal": ["chronic"], "tests": ["punctate_staining"], "exclusions": [] },

/* Medical retina — inflammatory / white-dot */
{ "name": "APMPPE (Acute Posterior Multifocal Placoid Pigment Epitheliopathy)", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma", "recent_viral_history"], "sup": ["reduced_vision", "young_age", "bilateral", "central_blur", "photophobia_mild"],
  "con": ["older_age", "pain", "redness", "night_blindness"], "temporal": ["acute"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Punctate Inner Choroidopathy (PIC)", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma", "myopia"], "sup": ["central_blur", "young_age", "distortion", "reduced_vision", "photophobia_mild"],
  "con": ["older_age", "pain", "redness", "night_blindness"], "temporal": ["subacute", "recurrent"], "tests": ["macular_screening_needed"], "exclusions": [] },

/* ═══ BATCH 6 (2026-07-15) — further high-yield gaps, specific required tokens
   + real contradictors. Provisional / NEEDS_CLINICAL_REVIEW. ═══ */

/* Ocular surface / lids */
{ "name": "Molluscum Contagiosum (Lid)", "domain": "Surface & Lids", "route": "surface",
  "req": ["painless_lid_nodule", "follicles"], "sup": ["chronic_redness", "watering", "foreign_body_sensation", "lid_margin_irregularity", "recurrent_episode"],
  "con": ["pain_severe", "purulent_discharge", "reduced_vision"], "temporal": ["chronic"], "tests": ["follicles"], "exclusions": [] },
{ "name": "Conjunctivochalasis", "domain": "Surface & Lids", "route": "surface",
  "req": ["excess_tearing", "foreign_body_sensation"], "sup": ["chronic_irritation", "older_age", "dryness", "redness", "burning"],
  "con": ["purulent_discharge", "itching_dominant", "sudden_onset"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* Cornea */
{ "name": "Corneal Dermoid", "domain": "Cornea", "route": "anterior",
  "req": ["limbal_nodule", "young_age"], "sup": ["astigmatism", "reduced_vision", "foreign_body_sensation", "chronic_irritation"],
  "con": ["pain_severe", "redness", "purulent_discharge", "sudden_onset"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Descemetocele", "domain": "Cornea", "route": "urgent",
  "req": ["corneal_thinning_central", "reduced_vision"], "sup": ["pain", "redness", "photophobia", "history_trauma_or_infection", "foreign_body_sensation"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute", "subacute"], "tests": [], "urgent": true, "exclusions": [] },

/* Vitreoretinal */
{ "name": "Asteroid Hyalosis", "domain": "Retina", "route": "retina",
  "req": ["floaters", "asteroid_hyalosis"], "sup": ["older_age", "vitreous_opacity", "reduced_contrast", "blur"],
  "con": ["pain", "redness", "flashes", "sudden_vision_loss", "field_loss"], "temporal": ["chronic"], "tests": ["asteroid_hyalosis"], "exclusions": [] },
{ "name": "Vitreous Amyloidosis", "domain": "Retina", "route": "retina",
  "req": ["floaters", "vitreous_opacity"], "sup": ["reduced_vision", "blur", "family_history", "vision_hazy", "gradual_blur"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": ["vitreous_opacity"], "exclusions": [] },
{ "name": "Familial Exudative Vitreoretinopathy (FEVR)", "domain": "Retina", "route": "retina",
  "req": ["peripheral_degeneration", "family_history"], "sup": ["reduced_vision", "young_age", "retinal_break", "field_loss", "floaters"],
  "con": ["older_age", "pain", "redness", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },

/* Glaucoma */
{ "name": "Phacolytic Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "white_cataract"], "sup": ["pain", "redness", "reduced_vision", "blur", "older_age", "halos"],
  "con": ["itching_dominant", "gradual_onset", "young_age"], "temporal": ["acute"], "tests": ["IOP_very_high"], "exclusions": [] },
{ "name": "Plateau Iris Syndrome", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["angle_closure_risk", "narrow_angle"], "sup": ["halos", "high_iop", "intermittent", "blur", "young_age"],
  "con": ["gradual_onset", "itching_dominant", "reduced_corneal_sensation"], "temporal": ["intermittent", "recurrent"], "tests": ["narrow_angle", "shallow_ac"], "exclusions": [] },

/* Motility / binocular */
{ "name": "Duane Retraction Syndrome", "domain": "Binocular Vision", "route": "binocular",
  "req": ["limited_abduction", "young_age"], "sup": ["head_tilt", "diplopia", "eye_inward", "restricted_motility"],
  "con": ["pain", "redness", "reduced_vision", "older_age"], "temporal": ["chronic"], "tests": ["restricted_motility"], "exclusions": [] },
{ "name": "Brown Syndrome", "domain": "Binocular Vision", "route": "binocular",
  "req": ["vertical_diplopia", "restricted_motility"], "sup": ["head_tilt", "diplopia", "young_age", "eye_down_out"],
  "con": ["pain_severe", "redness", "reduced_vision", "older_age"], "temporal": ["chronic"], "tests": ["restricted_motility"], "exclusions": [] },
{ "name": "Infantile (Congenital) Nystagmus", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["nystagmus_other_eye", "young_age"], "sup": ["reduced_vision", "head_tilt", "oscillopsia", "family_history"],
  "con": ["pain", "redness", "older_age", "sudden_vision_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ BATCH 7 (2026-07-16) — pediatric / leukocoria / necrotizing-retina and
   congenital gaps. Specific required tokens + real contradictors. Provisional /
   NEEDS_CLINICAL_REVIEW; the URGENT flags (retinoblastoma, ARN) especially. ═══ */

/* Vision/life-threatening pediatric */
{ "name": "Retinoblastoma", "domain": "Retina", "route": "urgent",
  "req": ["leukocoria", "young_age"], "sup": ["reduced_vision", "eye_inward", "family_history", "red_patch"],
  "con": ["older_age", "pain", "itching_dominant", "purulent_discharge"], "temporal": ["progressive"], "tests": ["macular_screening_needed"], "urgent": true, "exclusions": [] },
{ "name": "Ocular Toxocariasis", "domain": "Anterior / Uveitis", "route": "retina",
  "req": ["floaters", "young_age"], "sup": ["reduced_vision", "eye_inward", "vitreous_cells", "leukocoria"],
  "con": ["older_age", "pain_severe", "purulent_discharge", "itching_dominant"], "temporal": ["subacute", "chronic"], "tests": ["vitreous_cells"], "exclusions": [] },

/* Necrotizing retinitis (urgent, sight-threatening) */
{ "name": "Acute Retinal Necrosis (ARN)", "domain": "Retina", "route": "urgent",
  "req": ["pain", "floaters"], "sup": ["redness", "reduced_vision", "photophobia", "retinal_ischemia", "vitreous_cells", "field_loss"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["acute"], "tests": ["vitreous_cells"], "urgent": true, "exclusions": [] },
{ "name": "Cytomegalovirus (CMV) Retinitis", "domain": "Retina", "route": "retina",
  "req": ["floaters", "field_loss"], "sup": ["reduced_vision", "retinal_ischemia", "dark_spots", "autoimmune_history"],
  "con": ["pain_severe", "redness", "itching_dominant", "sudden_onset"], "temporal": ["subacute", "progressive"], "tests": [], "exclusions": [] },

/* Congenital anterior segment / glaucoma */
{ "name": "Primary Congenital Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["excess_tearing", "photophobia"], "sup": ["young_age", "corneal_edema", "high_iop", "spasm", "reduced_vision"],
  "con": ["older_age", "itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["chronic"], "tests": ["IOP_very_high"], "exclusions": [] },
{ "name": "Peters Anomaly", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity_central", "young_age"], "sup": ["reduced_vision", "leukocoria", "glare"],
  "con": ["older_age", "pain_severe", "redness", "itching_dominant"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Aniridia", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["photophobia", "transillumination_defects"], "sup": ["reduced_vision", "young_age", "glare", "nystagmus_other_eye", "family_history"],
  "con": ["pain", "redness", "older_age", "purulent_discharge"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* Congenital optic nerve / retina */
{ "name": "Optic Nerve Hypoplasia", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["reduced_vision", "nystagmus_other_eye"], "sup": ["young_age", "field_defect", "pale_disc", "family_history"],
  "con": ["pain", "redness", "older_age", "sudden_vision_loss"], "temporal": ["chronic"], "tests": ["pale_disc"], "exclusions": [] },
{ "name": "Chorioretinal Coloboma", "domain": "Retina", "route": "retina",
  "req": ["field_defect", "young_age"], "sup": ["reduced_vision", "leukocoria", "family_history", "peripheral_field_loss"],
  "con": ["pain", "redness", "older_age", "itching_dominant"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* Inherited cone / pigment */
{ "name": "Ocular Albinism", "domain": "Retina", "route": "retina",
  "req": ["nystagmus_other_eye", "glare"], "sup": ["photophobia", "reduced_vision", "young_age", "transillumination_defects", "family_history"],
  "con": ["pain", "redness", "older_age", "night_blindness"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Achromatopsia", "domain": "Retina", "route": "retina",
  "req": ["color_vision_loss", "photophobia"], "sup": ["reduced_vision", "young_age", "nystagmus_other_eye", "glare", "family_history"],
  "con": ["night_blindness", "pain", "redness", "older_age"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ BATCH 8 (2026-07-16) — larger batch (24). Distinct required-token pairs
   to avoid cross-firing; each carries real contradictors. Provisional /
   NEEDS_CLINICAL_REVIEW. Cross-conflict audit re-checked after adding. ═══ */

/* Cornea — dystrophies & degenerations */
{ "name": "Corneal Hydrops (Acute)", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_edema", "irregular_astigmatism"], "sup": ["pain", "photophobia", "reduced_vision", "watering", "young_age"],
  "con": ["itching_dominant", "gradual_onset", "older_age", "purulent_discharge"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Posterior Polymorphous Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["guttata", "family_history"], "sup": ["corneal_edema", "reduced_vision", "glare", "morning_blur"],
  "con": ["pain_severe", "redness", "itching_dominant", "purulent_discharge"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Schnyder Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity_central", "peripheral_corneal_ring_arcus"], "sup": ["reduced_vision", "family_history", "glare", "older_age"],
  "con": ["pain_severe", "redness", "itching_dominant", "purulent_discharge"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Meesmann Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["punctate_epithelial_lesions", "family_history"], "sup": ["foreign_body_sensation", "glare", "photophobia_mild", "recurrent_episode"],
  "con": ["pain_severe", "purulent_discharge", "older_age", "reduced_vision"], "temporal": ["chronic", "recurrent"], "tests": ["punctate_staining"], "exclusions": [] },
{ "name": "Macular Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity", "family_history"], "sup": ["reduced_vision", "glare", "photophobia_mild", "young_age", "foreign_body_sensation"],
  "con": ["pain_severe", "redness", "purulent_discharge", "older_age"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Congenital Hereditary Endothelial Dystrophy (CHED)", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_edema", "young_age"], "sup": ["reduced_vision", "family_history", "glare", "photophobia_mild"],
  "con": ["pain_severe", "redness", "older_age", "purulent_discharge"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Corneal Dellen", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_thinning", "foreign_body_sensation"], "sup": ["dryness", "reduced_tearing", "localized_conjunctival_elevation", "irritation"],
  "con": ["pain_severe", "purulent_discharge", "sudden_vision_loss"], "temporal": ["subacute"], "tests": [], "exclusions": [] },

/* Ocular surface */
{ "name": "Xerophthalmia (Vitamin A Deficiency)", "domain": "Surface & Lids", "route": "surface",
  "req": ["night_blindness", "dryness"], "sup": ["reduced_vision", "foreign_body_sensation", "chronic_irritation", "reduced_tearing"],
  "con": ["pain_severe", "purulent_discharge", "sudden_onset", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": ["punctate_staining"], "exclusions": [] },
{ "name": "Giant Fornix Syndrome", "domain": "Surface & Lids", "route": "surface",
  "req": ["chronic_redness", "purulent_discharge"], "sup": ["older_age", "recurrent_episode", "foreign_body_sensation", "reduced_vision", "ptosis"],
  "con": ["itching_dominant", "sudden_onset", "young_age"], "temporal": ["chronic", "recurrent"], "tests": [], "exclusions": [] },

/* Uveitis */
{ "name": "Juvenile Idiopathic Arthritis (JIA) Uveitis", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["young_age", "synechiae"], "sup": ["cells_present", "recurrent_episode", "corneal_opacity_band", "reduced_vision", "autoimmune_history"],
  "con": ["pain_severe", "purulent_discharge", "redness", "older_age"], "temporal": ["chronic", "recurrent"], "tests": ["cells_present"], "exclusions": [] },
{ "name": "Tubulointerstitial Nephritis & Uveitis (TINU)", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["cells_present", "autoimmune_history"], "sup": ["pain", "photophobia", "redness", "reduced_vision", "recurrent_episode", "young_age"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["acute", "recurrent"], "tests": ["cells_present"], "exclusions": [] },
{ "name": "Syphilitic Uveitis", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["cells_present", "floaters"], "sup": ["reduced_vision", "redness", "photophobia", "recurrent_episode", "vitreous_cells"],
  "con": ["itching_dominant", "purulent_discharge", "gradual_onset"], "temporal": ["subacute", "recurrent"], "tests": ["cells_present"], "exclusions": [] },

/* Neuro-ophthalmic */
{ "name": "Diabetic Papillopathy", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["disc_edema", "diabetes_history"], "sup": ["blur", "reduced_vision", "young_age", "field_defect"],
  "con": ["pain_severe", "itching_dominant", "redness", "sudden_vision_loss"], "temporal": ["subacute"], "tests": ["disc_edema"], "exclusions": [] },
{ "name": "Foster Kennedy Syndrome", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["disc_edema", "pale_disc"], "sup": ["reduced_vision", "headache", "field_defect", "color_vision_loss"],
  "con": ["pain_severe", "redness", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": ["pale_disc"], "exclusions": [] },
{ "name": "Tilted Disc Syndrome", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["tilted_disc", "myopia"], "sup": ["reduced_vision", "field_defect", "astigmatism", "young_age"],
  "con": ["pain", "redness", "older_age", "sudden_vision_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* Vitreoretinal / choroidal */
{ "name": "Terson Syndrome", "domain": "Retina", "route": "urgent",
  "req": ["vitreous_hemorrhage", "headache"], "sup": ["sudden_vision_loss", "reduced_vision", "floaters", "dark_spots"],
  "con": ["itching_dominant", "gradual_onset", "redness", "chronic_irritation"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Serpiginous Choroiditis", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma", "peripapillary_atrophy_beta_zone"], "sup": ["reduced_vision", "recurrent_episode", "distortion", "central_blur"],
  "con": ["pain", "redness", "young_age", "itching_dominant"], "temporal": ["recurrent", "chronic"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Leber Congenital Amaurosis", "domain": "Retina", "route": "retina",
  "req": ["nystagmus_other_eye", "night_blindness"], "sup": ["reduced_vision", "young_age", "family_history", "peripheral_field_loss"],
  "con": ["older_age", "pain", "redness", "sudden_vision_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Uveal Effusion Syndrome", "domain": "Retina", "route": "retina",
  "req": ["subretinal_fluid", "hyperopia"], "sup": ["reduced_vision", "field_loss", "choroidal_folds", "distortion"],
  "con": ["pain", "redness", "myopia", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Choroidal Effusion (Post-operative)", "domain": "Retina", "route": "retina",
  "req": ["choroidal_lesion_elevated", "post_surgery"], "sup": ["reduced_vision", "field_loss", "pain", "shadowing"],
  "con": ["itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["acute", "subacute"], "tests": [], "exclusions": [] },

/* Glaucoma */
{ "name": "Ghost Cell Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "vitreous_hemorrhage"], "sup": ["reduced_vision", "pain", "blur", "older_age", "halos"],
  "con": ["itching_dominant", "gradual_onset", "normal_iop"], "temporal": ["subacute"], "tests": ["IOP_very_high"], "exclusions": [] },

/* Lens */
{ "name": "Microspherophakia", "domain": "Lens", "route": "lens",
  "req": ["lens_displacement", "young_age"], "sup": ["myopia", "reduced_vision", "high_iop", "family_history", "glare"],
  "con": ["older_age", "pain", "redness", "purulent_discharge"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* Lids */
{ "name": "Blepharochalasis", "domain": "Surface & Lids", "route": "surface",
  "req": ["lid_swelling_diffuse", "recurrent_episode"], "sup": ["young_age", "ptosis", "localized_swelling", "chronic_irritation"],
  "con": ["pain_severe", "purulent_discharge", "reduced_vision"], "temporal": ["recurrent", "chronic"], "tests": [], "exclusions": [] },
{ "name": "Eyelid Capillary Hemangioma", "domain": "Surface & Lids", "route": "surface",
  "req": ["localized_lid_swelling", "young_age"], "sup": ["ptosis", "reduced_vision", "red_patch", "astigmatism"],
  "con": ["older_age", "pain_severe", "purulent_discharge", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },

/* ═══ BATCH 9 (2026-07-16) — continued expansion (17). Distinct required-token
   pairs; real contradictors. Provisional / NEEDS_CLINICAL_REVIEW. ═══ */

/* Medical / inflammatory retina */
{ "name": "Multifocal Choroiditis & Panuveitis", "domain": "Retina", "route": "retina",
  "req": ["floaters", "central_scotoma"], "sup": ["reduced_vision", "young_age", "myopia", "recurrent_episode", "vitreous_cells"],
  "con": ["pain_severe", "redness", "older_age", "itching_dominant"], "temporal": ["recurrent", "chronic"], "tests": ["macular_screening_needed"], "exclusions": [] },
{ "name": "Acute Zonal Occult Outer Retinopathy (AZOOR)", "domain": "Retina", "route": "retina",
  "req": ["central_scotoma", "flashes"], "sup": ["reduced_vision", "young_age", "field_defect", "recent_viral_history"],
  "con": ["pain", "redness", "older_age", "itching_dominant"], "temporal": ["acute", "subacute"], "tests": [], "exclusions": [] },
{ "name": "Cancer-Associated Retinopathy (CAR)", "domain": "Retina", "route": "retina",
  "req": ["night_blindness", "photophobia"], "sup": ["reduced_vision", "older_age", "central_scotoma", "field_loss", "flashes"],
  "con": ["young_age", "pain", "redness", "itching_dominant"], "temporal": ["subacute", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Eales Disease", "domain": "Retina", "route": "retina",
  "req": ["floaters", "vitreous_hemorrhage"], "sup": ["reduced_vision", "young_age", "retinal_ischemia", "nve_neovascularization_elsewhere", "sudden_floaters"],
  "con": ["pain_severe", "redness", "older_age", "itching_dominant"], "temporal": ["recurrent", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Hypotony Maculopathy", "domain": "Retina", "route": "retina",
  "req": ["distortion", "post_surgery"], "sup": ["reduced_vision", "central_blur", "choroidal_folds", "micropsia"],
  "con": ["high_iop", "itching_dominant", "redness", "sudden_vision_loss"], "temporal": ["subacute", "chronic"], "tests": [], "exclusions": [] },

/* Neuro-vascular / orbital */
{ "name": "Susac Syndrome", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["field_loss", "headache"], "sup": ["reduced_vision", "young_age", "retinal_ischemia", "central_scotoma"],
  "con": ["itching_dominant", "redness", "older_age", "purulent_discharge"], "temporal": ["subacute", "recurrent"], "tests": [], "exclusions": [] },
{ "name": "Orbital Rhabdomyosarcoma", "domain": "Neuro-Ophthalmic", "route": "urgent",
  "req": ["proptosis", "young_age"], "sup": ["reduced_vision", "restricted_motility", "ptosis", "red_patch", "diplopia"],
  "con": ["older_age", "itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["acute", "progressive"], "tests": ["restricted_motility"], "urgent": true, "exclusions": [] },
{ "name": "Orbital Lymphoma", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["proptosis", "older_age"], "sup": ["reduced_vision", "restricted_motility", "ptosis", "diplopia", "localized_conjunctival_elevation"],
  "con": ["young_age", "pain_severe", "sudden_onset", "purulent_discharge"], "temporal": ["chronic", "progressive"], "tests": ["restricted_motility"], "exclusions": [] },

/* Glaucoma */
{ "name": "Schwartz-Matsuo Syndrome", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "retinal_break"], "sup": ["reduced_vision", "floaters", "field_loss", "flashes"],
  "con": ["normal_iop", "itching_dominant", "gradual_onset"], "temporal": ["subacute"], "tests": ["IOP_very_high"], "exclusions": [] },

/* Cornea — degenerations */
{ "name": "Gelatinous Drop-like Corneal Dystrophy", "domain": "Cornea", "route": "anterior",
  "req": ["subepithelial_nodules", "family_history"], "sup": ["reduced_vision", "photophobia", "watering", "foreign_body_sensation", "young_age"],
  "con": ["pain_severe", "purulent_discharge", "older_age"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Spheroidal Degeneration (Climatic Droplet Keratopathy)", "domain": "Cornea", "route": "anterior",
  "req": ["corneal_opacity_peripheral", "older_age"], "sup": ["reduced_vision", "glare", "chronic_irritation", "foreign_body_sensation"],
  "con": ["pain_severe", "redness", "young_age", "purulent_discharge"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* Ocular surface / adnexa */
{ "name": "Stevens-Johnson Syndrome (Ocular)", "domain": "Surface & Lids", "route": "urgent",
  "req": ["redness", "fever"], "sup": ["pain", "purulent_discharge", "reduced_vision", "foreign_body_sensation", "cracking_skin", "photophobia"],
  "con": ["itching_dominant", "gradual_onset", "chronic_irritation"], "temporal": ["acute"], "tests": [], "urgent": true, "exclusions": [] },
{ "name": "Trachoma", "domain": "Surface & Lids", "route": "surface",
  "req": ["follicles", "trichiasis"], "sup": ["chronic_redness", "reduced_vision", "corneal_opacity", "entropion", "foreign_body_sensation"],
  "con": ["sudden_onset", "itching_dominant", "purulent_discharge"], "temporal": ["chronic"], "tests": ["follicles"], "exclusions": [] },
{ "name": "Ophthalmia Neonatorum", "domain": "Surface & Lids", "route": "surface",
  "req": ["purulent_discharge", "young_age"], "sup": ["redness", "lid_swelling_diffuse", "chemosis", "watering"],
  "con": ["itching_dominant", "older_age", "gradual_onset"], "temporal": ["acute"], "tests": [], "exclusions": [] },
{ "name": "Conjunctival Lymphoma", "domain": "Surface & Lids", "route": "surface",
  "req": ["localized_conjunctival_elevation", "chronic_redness"], "sup": ["older_age", "reduced_tearing", "foreign_body_sensation", "red_patch"],
  "con": ["pain_severe", "purulent_discharge", "sudden_onset", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Conjunctival Pyogenic Granuloma", "domain": "Surface & Lids", "route": "surface",
  "req": ["red_patch", "post_surgery"], "sup": ["localized_conjunctival_elevation", "watering", "foreign_body_sensation", "recent_eye_trauma"],
  "con": ["itching_dominant", "gradual_onset", "reduced_vision"], "temporal": ["subacute"], "tests": [], "exclusions": [] },
{ "name": "Dacryolithiasis", "domain": "Surface & Lids", "route": "surface",
  "req": ["excess_tearing", "medial_canthus_swelling"], "sup": ["recurrent_episode", "foreign_body_sensation", "discharge", "chronic_irritation"],
  "con": ["itching_dominant", "sudden_vision_loss", "purulent_discharge"], "temporal": ["recurrent", "chronic"], "tests": [], "exclusions": [] },

/* ═══ Batch 10 (2026-07-17) — posterior-segment tumours & vasculitis ═══ */
{ "name": "Choroidal Osteoma", "domain": "Retina", "route": "retina",
  "req": ["choroidal_lesion_elevated", "distortion"], "sup": ["gradual_blur", "central_scotoma", "reduced_vision", "young_age", "choroidal_folds"],
  "con": ["pain", "redness", "itching_dominant", "flashes", "sudden_vision_loss"], "temporal": ["chronic", "progressive"], "tests": ["choroidal_lesion_elevated"], "exclusions": [] },
{ "name": "Sclerochoroidal Calcification", "domain": "Retina", "route": "retina",
  "req": ["choroidal_lesion_elevated", "older_age"], "sup": ["reduced_vision", "gradual_blur", "field_loss", "choroidal_folds"],
  "con": ["pain", "redness", "itching_dominant", "sudden_vision_loss", "distortion"], "temporal": ["chronic"], "tests": ["choroidal_lesion_elevated"], "exclusions": [] },
{ "name": "Retinal Cavernous Hemangioma", "domain": "Retina", "route": "retina",
  "req": ["sectoral_hemorrhage", "floaters"], "sup": ["reduced_vision", "vitreous_hemorrhage", "young_age", "field_loss"],
  "con": ["pain", "redness", "itching_dominant", "gradual_blur", "photophobia"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Frosted Branch Angiitis", "domain": "Retina", "route": "retina",
  "req": ["vitreous_cells", "reduced_vision"], "sup": ["floaters", "flame_hemorrhages", "sectoral_hemorrhage", "field_loss"],
  "con": ["itching_dominant", "gradual_onset", "older_age", "gradual_blur"], "temporal": ["acute", "subacute"], "tests": [], "exclusions": [] },
{ "name": "Bietti Crystalline Dystrophy", "domain": "Retina", "route": "retina",
  "req": ["night_blindness", "central_scotoma"], "sup": ["glare", "reduced_vision", "field_loss", "gradual_blur"],
  "con": ["pain", "redness", "sudden_vision_loss", "distortion", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },

/* ═══ Batch 11 (2026-07-17) — intraocular tumours & disc anomalies (new tokens) ═══ */
{ "name": "Iris Melanoma", "domain": "Anterior / Uveitis", "route": "anterior",
  "req": ["iris_mass_lesion"], "sup": ["heterochromia", "reduced_vision", "older_age", "glare", "distortion", "pigment_dispersion"],
  "con": ["pain", "redness", "itching_dominant", "photophobia", "sudden_onset"], "temporal": ["chronic", "progressive"], "tests": ["iris_mass_lesion"], "exclusions": [] },
{ "name": "Optic Disc Melanocytoma", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["dark_disc_lesion"], "sup": ["reduced_vision", "field_loss", "central_scotoma"],
  "con": ["pain", "redness", "distortion", "itching_dominant", "sudden_vision_loss"], "temporal": ["chronic"], "tests": ["dark_disc_lesion"], "exclusions": [] },
{ "name": "Retinal Astrocytic Hamartoma", "domain": "Retina", "route": "retina",
  "req": ["retinal_astrocytic_lesion"], "sup": ["reduced_vision", "floaters", "young_age", "distortion"],
  "con": ["pain", "redness", "itching_dominant", "gradual_onset", "purulent_discharge"], "temporal": ["chronic"], "tests": ["retinal_astrocytic_lesion"], "exclusions": [] },
{ "name": "Optic Disc Coloboma", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["disc_coloboma"], "sup": ["field_loss", "reduced_vision", "young_age", "central_scotoma", "distortion"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant", "older_age"], "temporal": ["chronic"], "tests": ["disc_coloboma"], "exclusions": [] },
{ "name": "Choroidal Metastasis", "domain": "Retina", "route": "retina",
  "req": ["choroidal_lesion_elevated", "reduced_vision"], "sup": ["distortion", "field_loss", "central_scotoma", "gradual_blur"],
  "con": ["young_age", "itching_dominant", "pain", "redness", "flashes"], "temporal": ["subacute", "progressive"], "tests": ["choroidal_lesion_elevated"], "exclusions": [] },

/* ═══ Batch 12 (2026-07-17) — common Lens conditions (+20-per-area drive) ═══ */
{ "name": "Mature Cataract", "domain": "Lens", "route": "lens",
  "req": ["white_cataract"], "sup": ["gradual_blur", "reduced_vision", "older_age", "glare", "leukocoria"],
  "con": ["sudden_vision_loss", "pain", "redness", "flashes", "itching_dominant"], "temporal": ["chronic", "progressive"], "tests": ["white_cataract"], "exclusions": [] },
{ "name": "Hypermature (Morgagnian) Cataract", "domain": "Lens", "route": "lens",
  "req": ["morgagnian_cataract"], "sup": ["white_cataract", "reduced_vision", "older_age", "gradual_blur"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant", "flashes"], "temporal": ["chronic"], "tests": ["morgagnian_cataract"], "exclusions": [] },
{ "name": "Intumescent Cataract", "domain": "Lens", "route": "lens",
  "req": ["white_cataract", "shallow_ac"], "sup": ["reduced_vision", "older_age", "halos", "raised_iop_risk"],
  "con": ["itching_dominant", "sudden_vision_loss", "redness", "flashes"], "temporal": ["subacute"], "tests": ["white_cataract"], "exclusions": [] },
{ "name": "Anterior Subcapsular Cataract", "domain": "Lens", "route": "lens",
  "req": ["anterior_subcapsular_opacity"], "sup": ["gradual_blur", "glare", "reduced_vision", "near_blur"],
  "con": ["sudden_vision_loss", "pain", "redness", "flashes", "field_loss"], "temporal": ["progressive"], "tests": ["anterior_subcapsular_opacity"], "exclusions": [] },
{ "name": "Pseudoexfoliation (Lens Deposition)", "domain": "Lens", "route": "lens",
  "req": ["pxf_material"], "sup": ["gradual_blur", "older_age", "glare", "raised_iop_risk"],
  "con": ["itching_dominant", "sudden_onset", "pain", "redness"], "temporal": ["chronic"], "tests": ["pxf_material"], "exclusions": [] },
{ "name": "Anterior Lenticonus", "domain": "Lens", "route": "lens",
  "req": ["lenticonus"], "sup": ["irregular_astigmatism", "gradual_blur", "reduced_vision", "family_history"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant", "flashes"], "temporal": ["progressive"], "tests": ["lenticonus"], "exclusions": [] },
{ "name": "Christmas-Tree Cataract", "domain": "Lens", "route": "lens",
  "req": ["polychromatic_cataract"], "sup": ["glare", "gradual_blur", "older_age", "reduced_vision"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant", "flashes"], "temporal": ["chronic"], "tests": ["polychromatic_cataract"], "exclusions": [] },
{ "name": "Diabetic Snowflake Cataract", "domain": "Lens", "route": "lens",
  "req": ["snowflake_cataract"], "sup": ["gradual_blur", "young_age", "reduced_vision", "diabetes_history"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant", "older_age"], "temporal": ["subacute", "progressive"], "tests": ["snowflake_cataract"], "exclusions": [] },
{ "name": "IOL Dislocation", "domain": "Lens", "route": "lens",
  "req": ["iol_decentered"], "sup": ["ghosting", "distance_blur", "reduced_vision", "post_surgery"],
  "con": ["itching_dominant", "redness", "pain", "purulent_discharge"], "temporal": ["variable"], "tests": ["iol_decentered"], "exclusions": [] },
{ "name": "Aphakia", "domain": "Lens", "route": "lens",
  "req": ["aphakia"], "sup": ["distance_blur", "reduced_vision", "post_surgery", "gradual_blur"],
  "con": ["itching_dominant", "redness", "pain", "flashes"], "temporal": ["variable"], "tests": ["aphakia"], "exclusions": [] },

/* ═══ Batch 13 (2026-07-17) — common Refractive & Binocular conditions ═══ */
{ "name": "High (Pathological) Myopia", "domain": "Refractive", "route": "refractive",
  "req": ["high_myopia"], "sup": ["distance_blur", "reduced_vision", "family_history", "floaters", "glare"],
  "con": ["itching_dominant", "redness", "pain", "near_blur", "sudden_onset"], "temporal": ["chronic", "progressive"], "tests": [], "exclusions": [] },
{ "name": "Aniseikonia", "domain": "Refractive", "route": "refractive",
  "req": ["image_size_difference"], "sup": ["eye_strain", "headache", "difficulty_reading", "near_strain"],
  "con": ["itching_dominant", "redness", "pain", "sudden_vision_loss", "flashes"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Irregular Astigmatism", "domain": "Refractive", "route": "refractive",
  "req": ["irregular_astigmatism"], "sup": ["distance_blur", "ghosting", "glare", "reduced_vision", "fluctuating_blur"],
  "con": ["itching_dominant", "redness", "pain", "sudden_vision_loss", "field_loss"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Infantile (Congenital) Esotropia", "domain": "Binocular Vision", "route": "binocular",
  "req": ["eye_inward", "young_age"], "sup": ["constant_deviation", "family_history", "manifest_squint", "abnormal_head_posture"],
  "con": ["diplopia", "near_strain", "older_age", "gradual_onset"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Dissociated Vertical Deviation (DVD)", "domain": "Binocular Vision", "route": "binocular",
  "req": ["vertical_eye_drift"], "sup": ["manifest_squint", "young_age", "family_history", "abnormal_head_posture"],
  "con": ["diplopia", "pain", "redness", "itching_dominant"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Pseudostrabismus", "domain": "Binocular Vision", "route": "binocular",
  "req": ["manifest_squint", "young_age"], "sup": ["family_history", "abnormal_head_posture", "squinting"],
  "con": ["diplopia", "constant_deviation", "reduced_vision", "eye_strain"], "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ Batch 14 (2026-07-17) — common Retina conditions (sign-rich, new tokens) ═══ */
{ "name": "Retinal Arterial Embolus (Hollenhorst Plaque)", "domain": "Retina", "route": "retina",
  "req": ["retinal_embolus"], "sup": ["transient_vision_loss", "reduced_vision", "older_age", "field_loss"],
  "con": ["itching_dominant", "redness", "pain", "gradual_blur", "young_age"], "temporal": ["acute", "variable"], "tests": ["retinal_embolus"], "exclusions": [] },
{ "name": "Branch Retinal Artery Occlusion (BRAO)", "domain": "Retina", "route": "retina",
  "req": ["sectoral_retinal_infarct"], "sup": ["field_loss", "sudden_vision_loss", "retinal_embolus", "reduced_vision"],
  "con": ["itching_dominant", "redness", "pain", "gradual_blur"], "temporal": ["acute"], "tests": ["sectoral_retinal_infarct"], "exclusions": [] },
{ "name": "Roth Spots", "domain": "Retina", "route": "retina",
  "req": ["roth_spots"], "sup": ["reduced_vision", "floaters", "field_loss"],
  "con": ["itching_dominant", "pain", "redness", "gradual_blur", "distortion"], "temporal": ["acute", "subacute"], "tests": ["roth_spots"], "exclusions": [] },
{ "name": "Hydroxychloroquine (Plaquenil) Retinopathy", "domain": "Retina", "route": "retina",
  "req": ["bulls_eye_maculopathy"], "sup": ["central_scotoma", "reduced_vision", "difficulty_reading", "glare"],
  "con": ["pain", "redness", "sudden_vision_loss", "itching_dominant", "flashes"], "temporal": ["chronic", "progressive"], "tests": ["bulls_eye_maculopathy"], "exclusions": [] },
{ "name": "Congenital Hypertrophy of the RPE (CHRPE)", "domain": "Retina", "route": "retina",
  "req": ["rpe_hypertrophy_lesion"], "sup": ["young_age", "field_loss"],
  "con": ["reduced_vision", "pain", "redness", "distortion", "sudden_vision_loss"], "temporal": ["chronic"], "tests": ["rpe_hypertrophy_lesion"], "exclusions": [] },
{ "name": "Grouped Pigmentation (Bear Tracks)", "domain": "Retina", "route": "retina",
  "req": ["grouped_pigmentation"], "sup": ["young_age", "family_history"],
  "con": ["reduced_vision", "pain", "redness", "distortion", "sudden_vision_loss"], "temporal": ["chronic"], "tests": ["grouped_pigmentation"], "exclusions": [] },
{ "name": "Torpedo Maculopathy", "domain": "Retina", "route": "retina",
  "req": ["torpedo_lesion"], "sup": ["young_age", "central_scotoma"],
  "con": ["pain", "redness", "sudden_vision_loss", "distortion", "itching_dominant"], "temporal": ["chronic"], "tests": ["torpedo_lesion"], "exclusions": [] },
{ "name": "Myelinated Nerve Fibres", "domain": "Retina", "route": "retina",
  "req": ["myelinated_nerve_fibres"], "sup": ["field_loss", "young_age"],
  "con": ["reduced_vision", "pain", "redness", "distortion", "sudden_vision_loss"], "temporal": ["chronic"], "tests": ["myelinated_nerve_fibres"], "exclusions": [] },
{ "name": "Retinal Pigment Epithelial Detachment (PED)", "domain": "Retina", "route": "retina",
  "req": ["rpe_detachment"], "sup": ["distortion", "central_scotoma", "reduced_vision", "gradual_blur"],
  "con": ["pain", "redness", "itching_dominant", "flashes", "field_loss"], "temporal": ["subacute", "chronic"], "tests": ["rpe_detachment"], "exclusions": [] },
{ "name": "Snail-track Degeneration", "domain": "Retina", "route": "retina",
  "req": ["snailtrack_degeneration"], "sup": ["floaters", "flashes", "young_age"],
  "con": ["pain", "redness", "itching_dominant", "reduced_vision"], "temporal": ["chronic"], "tests": ["snailtrack_degeneration"], "exclusions": [] },
{ "name": "Peripheral Cystoid Degeneration", "domain": "Retina", "route": "retina",
  "req": ["peripheral_cystoid"], "sup": ["older_age", "field_loss"],
  "con": ["reduced_vision", "pain", "redness", "flashes", "distortion"], "temporal": ["chronic"], "tests": ["peripheral_cystoid"], "exclusions": [] },

/* ═══ Batch 15 (2026-07-17) — common Surface & Lids / adnexal conditions ═══ */
{ "name": "Dermatochalasis", "domain": "Surface & Lids", "route": "surface",
  "req": ["excess_lid_skin"], "sup": ["older_age", "field_loss", "abnormal_head_posture", "chronic_irritation"],
  "con": ["pain", "redness", "itching_dominant", "reduced_vision", "discharge"], "temporal": ["chronic", "progressive"], "tests": ["excess_lid_skin"], "exclusions": [] },
{ "name": "Xanthelasma", "domain": "Surface & Lids", "route": "surface",
  "req": ["xanthelasma_plaque"], "sup": ["older_age", "family_history"],
  "con": ["pain", "redness", "itching_dominant", "reduced_vision", "discharge", "foreign_body_sensation"], "temporal": ["chronic"], "tests": ["xanthelasma_plaque"], "exclusions": [] },
{ "name": "Eyelid Papilloma", "domain": "Surface & Lids", "route": "surface",
  "req": ["lid_papilloma"], "sup": ["chronic_irritation", "foreign_body_sensation", "older_age"],
  "con": ["pain_severe", "sudden_vision_loss", "reduced_vision", "field_loss", "purulent_discharge"], "temporal": ["chronic"], "tests": ["lid_papilloma"], "exclusions": [] },
{ "name": "Eyelid Epidermoid / Sebaceous Cyst", "domain": "Surface & Lids", "route": "surface",
  "req": ["lid_cyst"], "sup": ["lid_edema_localized", "foreign_body_sensation", "chronic_irritation"],
  "con": ["pain_severe", "reduced_vision", "sudden_vision_loss", "purulent_discharge", "field_loss"], "temporal": ["chronic"], "tests": ["lid_cyst"], "exclusions": [] },
{ "name": "Distichiasis", "domain": "Surface & Lids", "route": "surface",
  "req": ["extra_lash_row"], "sup": ["foreign_body_sensation", "watering", "chronic_irritation", "redness"],
  "con": ["itching_dominant", "sudden_vision_loss", "reduced_vision", "purulent_discharge"], "temporal": ["chronic"], "tests": ["extra_lash_row"], "exclusions": [] },
{ "name": "Eyelid Contact Dermatitis", "domain": "Surface & Lids", "route": "surface",
  "req": ["lid_dermatitis"], "sup": ["itching_dominant", "redness", "lid_edema_diffuse", "chronic_irritation"],
  "con": ["reduced_vision", "pain_severe", "purulent_discharge", "sudden_vision_loss"], "temporal": ["acute", "subacute"], "tests": ["lid_dermatitis"], "exclusions": [] },
{ "name": "Phthiriasis Palpebrarum (Lice)", "domain": "Surface & Lids", "route": "surface",
  "req": ["lash_lice"], "sup": ["itching_dominant", "chronic_irritation", "lid_margin_irregularity", "redness"],
  "con": ["reduced_vision", "sudden_vision_loss", "pain_severe", "purulent_discharge"], "temporal": ["chronic"], "tests": ["lash_lice"], "exclusions": [] },
{ "name": "Congenital Ptosis", "domain": "Surface & Lids", "route": "surface",
  "req": ["ptosis", "young_age"], "sup": ["abnormal_head_posture", "family_history", "reduced_vision"],
  "con": ["diplopia", "pain", "redness", "older_age", "sudden_onset"], "temporal": ["chronic"], "tests": ["ptosis"], "exclusions": [] },
{ "name": "Symblepharon", "domain": "Surface & Lids", "route": "surface",
  "req": ["symblepharon"], "sup": ["chronic_redness", "reduced_tearing", "foreign_body_sensation", "diplopia"],
  "con": ["itching_dominant", "sudden_vision_loss", "purulent_discharge"], "temporal": ["chronic"], "tests": ["symblepharon"], "exclusions": [] },
{ "name": "Conjunctival Concretions", "domain": "Surface & Lids", "route": "surface",
  "req": ["conjunctival_concretions"], "sup": ["foreign_body_sensation", "chronic_irritation", "older_age"],
  "con": ["reduced_vision", "sudden_vision_loss", "pain_severe", "purulent_discharge"], "temporal": ["chronic"], "tests": ["conjunctival_concretions"], "exclusions": [] },
{ "name": "Chemosis (Conjunctival Edema)", "domain": "Surface & Lids", "route": "surface",
  "req": ["conjunctival_edema"], "sup": ["lid_edema_diffuse", "itching_dominant", "redness", "watering"],
  "con": ["reduced_vision", "gradual_blur", "sudden_vision_loss"], "temporal": ["acute", "subacute"], "tests": ["conjunctival_edema"], "exclusions": [] },

/* ═══ Batch 16 (2026-07-17) — genuinely-missing common entry ═══ */
{ "name": "Pseudophakia", "domain": "Lens", "route": "lens",
  "req": ["iol_in_bag"], "sup": ["post_surgery", "glare", "halos", "reduced_vision", "post_cataract_surgery_blur"],
  "con": ["pain", "redness", "itching_dominant", "flashes"], "temporal": ["variable"], "tests": ["iol_in_bag"], "exclusions": [] },

/* ═══ Batch 17 (2026-07-18) — genuinely-missing common conditions ═══ */
{ "name": "Computer Vision Syndrome (Digital Eye Strain)", "domain": "Binocular Vision", "route": "binocular",
  "req": ["screen_use_exacerbation"], "sup": ["asthenopia", "eye_strain", "headache", "worse_evening", "dryness", "fluctuating_blur", "difficulty_near"],
  "con": ["sudden_vision_loss", "pain_severe", "redness", "flashes", "field_loss"], "temporal": ["chronic", "intermittent"], "tests": [], "exclusions": [] },
{ "name": "Strabismic Amblyopia", "domain": "Binocular Vision", "route": "binocular",
  "req": ["reduced_vision", "manifest_squint"], "sup": ["suppression", "unequal_vision", "young_age", "family_history"],
  "con": ["sudden_onset", "pain", "redness", "older_age"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Photokeratitis", "domain": "Cornea", "route": "anterior",
  "req": ["pain_severe", "uv_exposure"], "sup": ["photophobia", "foreign_body_sensation", "watering", "redness", "bilateral"],
  "con": ["gradual_onset", "itching_dominant", "purulent_discharge"], "temporal": ["acute", "sudden_onset"], "tests": [], "exclusions": [] },
{ "name": "Vitreous Floaters (Benign)", "domain": "Retina", "route": "retina",
  "req": ["floaters"], "sup": ["gradual_onset", "older_age"], "con": ["flashes", "sudden_vision_loss", "field_loss", "reduced_vision"],
  "temporal": ["chronic"], "tests": [], "exclusions": [] },

/* ═══ Batch 18 (2026-07-18) — genuinely-missing common conditions ═══ */
{ "name": "Anisometropic Amblyopia", "domain": "Binocular Vision", "route": "binocular",
  "req": ["reduced_vision", "unequal_refractive_error"], "sup": ["suppression", "unequal_vision", "young_age", "family_history"],
  "con": ["manifest_squint", "sudden_onset", "pain", "older_age"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Uveitic Glaucoma", "domain": "Glaucoma", "route": "glaucoma",
  "req": ["high_iop", "cells_present"], "sup": ["keratic_precipitates", "reduced_vision"],
  "con": ["itching_dominant", "gradual_onset", "normal_iop"], "temporal": ["acute", "subacute"], "tests": ["high_iop"], "exclusions": [] },
{ "name": "Contact Lens Overwear (Corneal Hypoxia)", "domain": "Cornea", "route": "anterior",
  "req": ["contact_lens_intolerance", "pain"], "sup": ["redness", "photophobia", "foreign_body_sensation", "watering", "reduced_wear_time"],
  "con": ["gradual_onset", "itching_dominant", "purulent_discharge"], "temporal": ["acute", "subacute"], "tests": [], "exclusions": [] },
{ "name": "Latent Nystagmus", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["nystagmus_other_eye"], "sup": ["manifest_squint", "young_age", "suppression", "reduced_vision"],
  "con": ["older_age", "sudden_onset", "pain"], "temporal": ["chronic"], "tests": [], "exclusions": [] },
{ "name": "Optic Disc Drusen", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["disc_drusen"], "sup": ["field_loss"], "con": ["reduced_vision", "sudden_vision_loss", "pain"],
  "temporal": ["chronic"], "tests": ["disc_drusen"], "exclusions": [] },

/* ═══ Batch 19 (2026-07-18) — genuinely-missing common conditions ═══ */
{ "name": "Facial Nerve Palsy (Bell's) — Ocular", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["lagophthalmos", "sudden_onset"], "sup": ["dryness", "foreign_body_sensation", "watering", "redness"],
  "con": ["reduced_vision", "itching_dominant", "gradual_onset", "diplopia"], "temporal": ["acute", "sudden_onset"], "tests": ["lagophthalmos"], "exclusions": [] },
{ "name": "Ophthalmoplegic Migraine", "domain": "Neuro-Ophthalmic", "route": "neuro",
  "req": ["diplopia", "headache"], "sup": ["restricted_motility", "ptosis", "vomiting", "photophobia"],
  "con": ["sudden_vision_loss", "gradual_onset"], "temporal": ["intermittent"], "tests": [], "exclusions": [] }

];
