/* ═══════════════════════════════════════════════════════════════ */
/* ENTOPIC — FOUNDER CLINICAL SIGN-OFFS (source of truth)          */
/*                                                                  */
/* Generated by the Admin panel's "Export sign-offs" button from    */
/* the founder's in-app verifications (Clinical Review Queue).      */
/* Each entry attests that the named clinician reviewed the         */
/* condition's findings, urgency flag, ICD code and About summary.  */
/*                                                                  */
/* To make sign-offs permanent across devices: export from the      */
/* Admin panel and replace this file's KB_VERIFIED object with the  */
/* downloaded content, then commit. The loader applies these at     */
/* boot (see knowledge/loader.js), so verified conditions no longer */
/* show as provisional anywhere.                                    */
/*                                                                  */
/* NEVER hand-edit clinical content here — this file carries review */
/* attestations only.                                               */
/* ═══════════════════════════════════════════════════════════════ */
"use strict";

var KB_VERIFIED = {
  /* "Condition Name": { on: "YYYY-MM-DD", by: "Clinician Name" } */
};
