#!/usr/bin/env node
/* Regenerate the parts of ARCHITECTURE.md that describe the code.
 *
 * The header counts and Appendix A were hand-written and went stale: the doc
 * claimed v1.1 and 72 files against an actual v1.4 and 97. tests/docs.test.js
 * now fails when they drift, and this is the thing that fixes the drift, so
 * nobody has to count script tags by hand.
 *
 *   node tools/sync-docs.js            update the doc to match the code
 *   node tools/sync-docs.js --check    exit 1 if it would change anything
 */
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const read = (f) => fs.readFileSync(path.join(ROOT, f), "utf8");
const lines = (f) => read(f).split("\n").length;

const html = read("index.html");
const order = [...html.matchAll(/<script src="([^"]+)"/g)].map((m) => m[1]);
const knowledge = order.filter((f) => f.startsWith("knowledge/"));
const js = order.filter((f) => f.startsWith("js/"));

const appVersion = /var APP_VERSION = "([^"]+)"/.exec(read("js/build-info.js"))[1];
const kbVersion = /var KB_VERSION = "([^"]+)"/.exec(read("js/build-info.js"))[1];

/* ── Appendix A, generated ── */
const inv = [];
inv.push("# APPENDIX A — File inventory\n");
inv.push("Generated by `node tools/sync-docs.js` from the `<script>` order in");
inv.push("`index.html`, which IS the dependency graph in a build-step-free app.");
inv.push(order.length + " loaded files.\n");
inv.push("**Root** — `index.html` (" + lines("index.html") + "), `css/entopic.css` (" +
  lines("css/entopic.css") + ")\n");
inv.push("**`/knowledge`** — " + knowledge.length + " files, loaded first, in this order:\n");
knowledge.forEach((f) => inv.push("- `" + f.replace("knowledge/", "") + "` (" + lines(f) + ")"));
inv.push("\n**`/js`** — " + js.length + " files, in load order:\n");
js.forEach((f) => inv.push("- `" + f.replace("js/", "") + "` (" + lines(f) + ")"));

const untracked = fs.readdirSync(path.join(ROOT, "js"))
  .filter((f) => f.endsWith(".js")).map((f) => "js/" + f)
  .filter((f) => !order.includes(f));
if (untracked.length) {
  inv.push("\n**Present in `/js` but NOT loaded by index.html** — dead unless something");
  inv.push("else pulls them in:\n");
  untracked.forEach((f) => inv.push("- `" + f + "`"));
}

let doc = read("ARCHITECTURE.md");
const before = doc;

const start = doc.indexOf("# APPENDIX A — File inventory");
const end = doc.indexOf("# APPENDIX B —");
if (start < 0 || end < 0) {
  console.error("ARCHITECTURE.md: could not find Appendix A/B markers.");
  process.exit(2);
}
doc = doc.slice(0, start) + inv.join("\n") + "\n\n---\n\n" + doc.slice(end);

doc = doc.replace(
  /\*\*Covers build:\*\* Entopic v[0-9.]+, KB v[0-9.]+ — \d+ loaded files \(\d+ in `js\/`, \d+ in\n`knowledge\/`\), (\d+) conditions across 9 domains, \d+ test files\./,
  "**Covers build:** Entopic v" + appVersion + ", KB v" + kbVersion + " — " + order.length +
  " loaded files (" + js.length + " in `js/`, " + knowledge.length + " in\n`knowledge/`), $1 conditions across 9 domains, " +
  fs.readdirSync(path.join(ROOT, "tests")).filter((f) => f.endsWith(".js")).length + " test files.");

if (process.argv.includes("--check")) {
  if (doc !== before) {
    console.error("ARCHITECTURE.md is out of date. Run: node tools/sync-docs.js");
    process.exit(1);
  }
  console.log("ARCHITECTURE.md is current.");
  process.exit(0);
}

fs.writeFileSync(path.join(ROOT, "ARCHITECTURE.md"), doc);
console.log("ARCHITECTURE.md synced — v" + appVersion + ", " + order.length + " loaded files.");
